"use client"
import { StoreProvider } from "easy-peasy"
import "./globals.css"
import { Inter } from "next/font/google"
import store from "../store"

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
  title: "Dashboard barang",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <StoreProvider store={store}>
        <body className={inter.className}>{children}</body>
      </StoreProvider>
    </html>
  )
}
